name: Auto Tag my Application
on:
    push:
        branches:
            - main

jobs:
    Patch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Minor version for each merge
              id: AutoTagger
              uses: anothrNick/github-tag-action@1.36.0
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
                WITH_V: true